pipeline {
    agent any
    stages {
        stage ('Build'){
            script {
                openshiftBuild(buildConfig: 'springboot-activemq', showBuildLogs: 'true')
            }
        }
        stage ('Deploy'){
            script {
                openshiftDeploy(deploymentConfig: 'springboot-activemq')
            }
        }
    }
}